### ISSUE TITLE
Allow for two mixed pronouns to display both.

### ISSUE THREAD

**Issue by strand** [witch-house/pronoun.is#38]
Hey, currently I link to pronoun.is with http://pronoun.is/they/him/their/his/them as either they or he pronouns work for me. This url is a bit unwieldy, and I was wondering if we could make it so something like http://pronoun.is/they/him would provide a mix of pronouns.

If someone would pair with me for long enough to get the app running in my local environment (I've never done Clojure before) I would be glad to implement this feature.

**Comment by morganastra** [comment]
Okay this is not the first time someone's asked for this, so while I had some resistance at first I'm willing to consider it.

One thing that needs a little design here is the url scheme. I wouldn't want to create any ambiguity, so ideally the url syntax should look a little bit different.

The other thing is, well, how would they be displayed? Two pronoun example divs side-by-side? One after the other? One block of examples with slashed alternatives in each place (e.g. "he/they went to the park")? I'm not sure, and very open to suggestions here.

**Comment by strand** [comment]
We could use `|` to indicate either…

I think that displaying pronouns in alternating sentences like http://pronoun.is/they/him/their/his/them already does would work great.

Would you have an hour this Sunday to videochat and pair on this?

**Comment by morganastra** [comment]
I'm into using `|` in the URL, etc. So like pronoun.is/they|he for you.

It's a little more complicated when more than one pronoun is required for disambiguation, like with ze/zir. If I were going to use ze or she, would that be pronoun.is/ze|she/zir|her or pronoun.is/ze/zir|she/her? The second is perhaps closer to how you would say it in spoken english but the url semantics are weird there since you expect an url to be broken up into path components before anything else.

I don't like displaying them as alternating sentences, I think that's confusing (for one thing, it changes pronouns mid-sentence which makes it sound like it's talking about two different people).

I'd be happy to pair with you for an hour Sunday, we can talk about the details via twitter dm

**Comment by morganastra** [comment]
Hey so @jneen and I were talking about this recently and came up with another alternative - using URL query parameters so that you could write http://pronoun.is/he?or=they

One advantage of this is that it preserves the property of pronoun.is links that, when read aloud ignoring punctuation, they are equivalent to the English phrase you would use to describe your pronouns. So, in your case, "my pronoun is he or they".

If that sounds good to you I'll go ahead and implement it and have it in the next release.

**Comment by strand** [comment]
💖 💖 💖 💖 💖 💖 💖 💖 💖 💖 

Thank you!
