### ISSUE TITLE
No be-verb examples

### ISSUE THREAD

**Issue by maco** [witch-house/pronoun.is#60]
None of the pronoun examples use a be-verb. 

* "He is over there" 
* "They are over there" 
* "Fey ____ over there" 

I can't tell whether "fey" should use "is" or "are."

**Comment by morganastra** [comment]
true. the omission is half-intentional; some pronouns could go either way, people even use "they" with singular conjugations of be in some contexts. specifying the plurality of the verb in every pronoun.is link would be tedious. and, the sentences have a lot of recognition now, so we are very hesitant to change them at all.

but be-verb examples would be nice to have. maybe someday.

**Comment by KirillOsenkov** [comment]
Came here to find out whether "Fey is" or "Fey are" is correct, would be nice to know.
